## Write a Numpy Program to create a vector of length¶

solution to question 1:

 1.Vector of length 5 filled with arbitrary integers from 0 to 10:

In [4]:
import numpy as np
x = np.random.randint(0, 11, 5)
print(x)

[ 4  5 10  6  0]


## Write a NumPy program to create a vector with values¶
​​ranging from 15 to 55 and print all values​​except the first and last.

solution to question 2

In [5]:
v = np.arange(15, 55)
print("Original vector:")
print(v)

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [6]:
print("All values except the first and last of the said vector:")
print(v[1:-1])

All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


## Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.

solution to question 3
1. Average of the array element 


In [7]:
x = np.random.randn(1000)
mean = x.mean()
print(mean)

0.018126823933622523


2. Standard deviation pf the array elements:

In [8]:
std = x.std()
print(std)

0.9839938511274913


3. Variance of the array element:

In [9]:
var = x.var()
print(var)

0.9682438990567114


## Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array.

Solution to question 4
1. Original Array

In [10]:
import numpy as np
x = np.array([[1, 2, 3],[4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


2. cumulative sum of the element along a given axis:

In [11]:
y = np.cumsum(x)
print(y)

[ 1  3  6 10 15 21]


3. sum over rows for each of the 3 columns :

In [12]:
y = np.cumsum(x,axis=0)
print(y)

[[1 2 3]
 [5 7 9]]


4. sum over columns for each of the 2 rows : 

In [13]:
y = np.cumsum(x,axis=1)
print(y)

[[ 1  3  6]
 [ 4  9 15]]


## Write a NumPy program to compute the multiplication of two given matrixes. 

Sample Matrix: 

[[1, 0], [0, 1]] 

[[1, 2], [3, 4]] 


solution to question 5

 1.Original Array 

In [14]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print(p)
print(q)
result1 = np.dot(p, q)

[[1, 0], [0, 1]]
[[1, 2], [3, 4]]


2. Result of the said metrix multiplication :

In [15]:
print(result1)

[[1 2]
 [3 4]]
